#pragma once

#ifndef STRUCTURED_SCRIPT_TYPENAME_H
#define STRUCTURED_SCRIPT_TYPENAME_H

namespace StructuredScript{
	enum Typename{
		TYPE_NAME_ANY,
		TYPE_NAME_VOID,
		TYPE_NAME_BOOLEAN,
		TYPE_NAME_BIT,
		TYPE_NAME_BYTE,
		TYPE_NAME_NAN,
		TYPE_NAME_CHAR,
		TYPE_NAME_UCHAR,
		TYPE_NAME_SHORT,
		TYPE_NAME_USHORT,
		TYPE_NAME_INT,
		TYPE_NAME_UINT,
		TYPE_NAME_LONG,
		TYPE_NAME_ULONG,
		TYPE_NAME_LLONG,
		TYPE_NAME_ULLONG,
		TYPE_NAME_FLOAT,
		TYPE_NAME_DOUBLE,
		TYPE_NAME_LDOUBLE,
		TYPE_NAME_STRING,
		TYPE_NAME_TYPE,
		TYPE_NAME_FUNCTION,
		TYPE_NAME_NONE
	};
}

#endif /* !STRUCTURED_SCRIPT_TYPENAME_H */